export enum AmenityKeys {
  CCTV_SECURITY = "CCTV_SECURITY",
  BASEMENT_PARKING = "BASEMENT_PARKING",
  SWIMMING_POOL = "SWIMMING_POOL",
  CAFE_LOUNGE = "CAFE_LOUNGE",
  AIR_CONDITIONING = "AIR_CONDITIONING",
  GYM = "GYM",
}
