export const productListMock = [
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "1",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/1",
  },
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "2",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/2",
  },
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "3",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/3",
  },
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "4",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/4",
  },
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "1",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/1",
  },
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "1",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/1",
  },
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "1",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/1",
  },
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "1",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/1",
  },
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "1",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/1",
  },
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "1",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/1",
  },
  {
    imageSrc: "/assets/images/building1.jpeg",
    id: "1",
    alt: "BKC 28 image",
    productName: "BKC 28",
    productCity: "Mumbai",
    url: "property-details/1",
  },
];
